# !/usr/bin/python

"""
Author:  Thomas Laurenson
Email:   thomas@thomaslaurenson.com
Website: thomaslaurenson.com
Date:    2016/02/23

Description:
printTimeTaken.py prints processing time of RegXML generated by CellXML-Registry.

Copyright (c) 2016, Thomas Laurenson
"""

import os
import sys
import glob

################################################################################
def parseLogFile(logfile):
    keys = 0
    values = 0
    dkeys = 0
    dvalues = 0
    time = 0

    with open(logfile) as f:
        for l in f:
            l = l.strip()
            if "ExportDataToXMLFormat INFO >>> total_values:" in l:
                l = l.split(">>>")
                l = l[1]
                l = l.split(":")
                l = l[1]
                values += int(l)
            elif "ExportDataToXMLFormat INFO >>> total_keys:" in l:
                l = l.split(">>>")
                l = l[1]
                l = l.split(":")
                l = l[1]
                keys += int(l)
            elif "ExportDataToXMLFormat INFO >>> total_deleted_keys:" in l:
                l = l.split(">>>")
                l = l[1]
                l = l.split(":")
                l = l[1]
                dkeys += int(l)
            elif "ExportDataToXMLFormat INFO >>> total_deleted_values:" in l:
                l = l.split(">>>")
                l = l[1]
                l = l.split(":")
                l = l[1]
                dvalues += int(l)        
            elif "CellXMLRegistry.Program Main INFO >>> Processing time:" in l:
                l = l.split(">>>")
                l = l[1]
                l = l.split(":")
                l = l[1]
                l = l.split("s")
                l = l[0]
                time += float(l)
    f.close()
                
    print("%s,%d,%d,%d,%d,%f" % (logfile, keys, values, dkeys, dvalues, time))
    
################################################################################
if __name__=="__main__":
    import argparse
    parser = argparse.ArgumentParser(description='''printTimeTaken.py''', formatter_class = argparse.RawTextHelpFormatter)
    parser.add_argument("logfile",
                        help = "CellXML-Registry log file, or directory of log files")

    args = parser.parse_args()

    logfile = args.logfile    
    
    # Print header
    print("%s,%s,%s,%s,%s,%s" % (logfile,
                                 "Keys",
                                 "Values",
                                 "DeletedKeys",
                                 "DeletedValues",
                                 "Time"))
    
    if os.path.isdir(logfile):
        logs = glob.glob(logfile + "/*.log")
        for log in logs:
            parseLogFile(log)
    else:
        parseLogFile(logfile)
     
